CREATE TABLE CART

(
    CART_NO INT(5) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_NO INT(5),
    FONT_NO INT(5),
    FOREIGN KEY (USER_NO)
    REFERENCES USERS(USER_NO) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (FONT_NO)
    REFERENCES FONTS(FONT_NO) ON UPDATE CASCADE ON DELETE CASCADE

);